### ISSUE TITLE
Apk not installable

### ISSUE THREAD

**Issue by Mikiya83** [Sky-84/hbs_decipher_for_Android#1]
Hi
You sent me the APK beta, but i can't install it. I get an error related to a "package problem". Did you sign your apk with your dev key ? I don't have ADB here to test with.
Thanks !

edit : i see you use _minSdkVersion=26_ (Android 8 Oreo) and _targetSdkVersion=29_ (Android 9 Pie), but android 8.0 + 8.1 + 9  are used by less than 25% of Android market (https://developer.android.com/about/dashboards/) so this seems too restrictive. I'm on Android 7 so i can't install it. _minSdkVersion=22_ (Android 5.1 Lollipop) or at least _minSdkVersion=23_ (Android 6 Marshmallow) seems more realistic. Try with the minimum version possible to be the most open to all users. ;)

**Comment by Sky-84** [comment]
Hi Yoann,
When I started the development I set the min sdk version of Android Ice Cream Sandwitch then I was forced to increase the value because in QNAPFileDecrypterEngine there are some classes not present in the previous Android API (e.g. java.nio.file.Files; java.nio.file.Paths;). I would have open the enhancement to you in next days but at least in this phase I wanted to see app working :).
The apk is not signed but I was able to install it in my smartphone enabling unknown sources app installation. If you are not able to install in this way, I will try to create an other apk later.
Bye

**Comment by Mikiya83** [comment]
I already have unknown sources enabled but i can't install it (i think it's caused by minSdkVersion, i'm on Android 7, so Sdk 24 ).
Indeed Files and Paths are problematics ... i can release a JAR without it if you want.
I understand it's only in beta stage, no problem ;)

**Comment by Sky-84** [comment]
If you can release a JAR without them I think this problem could be closed.
At the moment I'm in office and I can't check other classes :(, I can do this later when I come back to home.
Anyway thanks for your feedbacks :)

**Comment by Mikiya83** [comment]
At the moment I'm in office too, i can release it later. I will publish link here when it will be available.
Thanks

**Comment by Sky-84** [comment]
Hi,
the lines affected are:
- 447: Files.**deleteIfExists**(Paths.**get**(outputFile.getAbsolutePath() + TEMP_SUFFIX));
- 568: try (InputStream is = Files.**newInputStream**(Paths.**get**(file.getAbsolutePath()));

Changing these, I can set min sdk 19 (KitKat).
Thanks.

**Comment by Mikiya83** [comment]
Is it ok with this one (i only test it on few files so use it with cautions) ?
https://yoann-tritz.fr/documents/hybrid_backup_sync_decipher_1.4.4_beta.jar

**Comment by Sky-84** [comment]
It seems working ;)!
In attach the new apk that I also tested on a physical Android 6 smartphone with few files.
Let me know if you can install and launch it now.
Bye
[hbs_decipher_for_Android_v0.2.zip](https://github.com/Sky-84/hbs_decipher_for_Android/files/2814088/hbs_decipher_for_Android_v0.2.zip)

**Comment by Mikiya83** [comment]
Now i can install APK by ADB (not directly on phone, i get an error message but we will see that later).
It seems to work quite well, not bad for a first beta version 👍 UI still need to be a bit polish but it's cool to have it on Android ! Thanks 🥇 
I will raise another little bug but first, thank you for the port :)

**Comment by Sky-84** [comment]
I'm pleased to you were be able to launch it somehow and you like it :D.
For now I leave open this issue since we understand why you can't install directly the apk.
Thanks to you for the opportunity to have decipher engine almost ready for Android too ;)

**Comment by Sky-84** [comment]
I built a signed apk (in attach, it includes report too), maybe now you can install it without ADB.
[hbs_decipher_for_Android_v0.4.zip](https://github.com/Sky-84/hbs_decipher_for_Android/files/2818908/hbs_decipher_for_Android_v0.4.zip)

**Comment by Mikiya83** [comment]
I get an error message from Play Protect (because your signing key is not recognized by Google i think) but if  i disable it temporarly, it's ok i can install it. So now you just have to validate your signing key by Google ;)

**Comment by Sky-84** [comment]
Ok then, when it will be published there won't be any problem at all.

**Comment by Sky-84** [comment]
Maybe I was wrong and the signing process should complete correctly independently from publishing. 
I forgot to write here yesterday that I should have solved the failure on signing process :). Now you should be able to install the apk without errors ;).
