### ISSUE TITLE
Buttons disapearred when long paths are selected

### ISSUE THREAD

**Issue by Mikiya83** [Sky-84/hbs_decipher_for_Android#2]
Hi
A little UI bug : When i choose paths on 3 lines for source and folder (with start like "/storage/emulated/0/Download/MyPath..." it's not that hard to have long path unfortunately), the buttons are "flattens". It could be cool if a scroll bar can be displayed when UI needs it ;)
Thanks again for your work on it !

**Comment by Sky-84** [comment]
Good point :), I'll try to replicate the issue and fix it.

**Comment by Mikiya83** [comment]
On my phone : 
[![img-eggsif-2490410759950232592.png](https://i.postimg.cc/pVp6nHK6/img-eggsif-2490410759950232592.png)](https://postimg.cc/YjB3JTn6)
Tell me if you need anything to test/fix.

**Comment by Sky-84** [comment]
Scroll bar added :)
In attach the apk.
[hbs_decipher_for_Android_v0.5.zip](https://github.com/Sky-84/hbs_decipher_for_Android/files/2819195/hbs_decipher_for_Android_v0.5.zip)

**Comment by Mikiya83** [comment]
It seems ok, well done :)
