### ISSUE TITLE
HBSUtility_report.txt not created

### ISSUE THREAD

**Issue by Mikiya83** [Sky-84/hbs_decipher_for_Android#3]
I don't know if it's a bug or not ... 
Message says "HBSUtility_report.txt" is created after a decipher, but i can't find it in destination folder.
It's not a big problem because i don't know if it's really useful on phone... If you need changes in output messages from my lib, tell me i can do some adjustments on it ;)

**Comment by Sky-84** [comment]
You're right, no report file is created.
In this first release I have not implemented yet the method to write it, I'll do it in next days.
I think no changes are needed from your side, in case I'll let you know.

**Comment by Sky-84** [comment]
I inserted the method for the report.
Try the apk in attach (sorry but I think you have to install it via ADB again... then I'll try to create a signed apk).
[hbs_decipher_for_Android_v0.3.zip](https://github.com/Sky-84/hbs_decipher_for_Android/files/2818711/hbs_decipher_for_Android_v0.3.zip)

**Comment by Mikiya83** [comment]
I can confirm, report file is now created ! :) But i find a bug in my lib (when a QNAP-file is found, even if decipher fails because of bad password, it's write as "Success file", i fix it immediatly)

**Comment by Mikiya83** [comment]
JAR with boolean result fixed (so HBSUtility_report.txt now list as failed files with bad password) : 
https://yoann-tritz.fr/documents/hybrid_backup_sync_decipher_1.4.4_beta.jar

**Comment by Sky-84** [comment]
Perfect, thanks. 
I can close this issue.
