### ISSUE TITLE
[Ideas/Improvements] GUI changes

### ISSUE THREAD

**Issue by Mikiya83** [Sky-84/hbs_decipher_for_Android#4]
I create this "issue" only to give you my point of view on small UI changes. It's up to you to choose if you like them or not ! ;)

- ~~_Remove Password button_ : for me, the password should be stored as less as possible by the program. So instead of a Password button that store Password field in RAM, i prefer to ask password when user press "Decipher" button, use it at this moment and clear password variable immediatly.~~

- ~~_"Credit" / "About" menu_ : Just to tell people who and from how this software is made. It's could be useful because i think you will publish this APK on Play Store or F-Droid so it can help if people who download directly from stores have issues.~~

- ~~_Explicit icons_ : Last and minor evolution but icons can be improved. But it's normal on a beta app !! ;)~~

Thanks again for your work !! 👍

**Comment by Sky-84** [comment]
I agree with you for all points. 
I already try to implement the first point but it was taking too much time so I decided to postpone it. Android dialogs seem to have a more difficult management than java desktop ones so I have to go in deep.
For sure I have to insert a Credit section, I'll put it somewhere :). I don't know yet if I'll publish the app in the store or simply distribute the apk, I would like to understand better the potential licence\copyright overlapping.
Icons and in general grafic design are not my better abilities but I can try :D. Moreover it is still missing the "master" icon for the app drawer that I think it is mandatory for the app distribution.
As usual, thanks for your feedbacks, they are very useful.

**Comment by Mikiya83** [comment]
About icons, you can try to find one here : https://www.iconfinder.com/search/?q=lock&price=free
Licenses are clear (GPL, CC...) and without any charge.
I find for example : 

- https://www.iconfinder.com/icons/4021485/cloud_lock_protect_security_shield_icon

- https://www.iconfinder.com/icons/1055033/lock_locked_secure_icon

- https://www.iconfinder.com/icons/1311611/circle_lock_security_style_unlock_icon

**Comment by Sky-84** [comment]
> About icons, you can try to find one here : https://www.iconfinder.com/search/?q=lock&price=free
> Licenses are clear (GPL, CC...) and without any charge.
> I find for example :
> 
> * https://www.iconfinder.com/icons/4021485/cloud_lock_protect_security_shield_icon
> * https://www.iconfinder.com/icons/1055033/lock_locked_secure_icon
> * https://www.iconfinder.com/icons/1311611/circle_lock_security_style_unlock_icon

They are very nice and I decided to use the first one.
According to you, the CC BY licence is compatible with GPLv3 as overall license of the app?
I added the author and CC BY terms in the LICENSE file in the root, do you think is enogh?
Thanks :)

**Comment by Mikiya83** [comment]
Yes i think that as long as you credit the icon's author with it's license AND a note in your "About" screen (in the app), it's ok.
I like the first one too ^^
edit : don't mix two license in your license file, add CC-BY license file next to it, with a proper name like "Icon-LICENCE-CC BY" for example, it's cleaner.

**Comment by Sky-84** [comment]
In attach the apk with the "About" section and the master icon.
Let me know what do you think about it :).
[hbs_decipher_for_Android_v0.6.zip](https://github.com/Sky-84/hbs_decipher_for_Android/files/2825957/hbs_decipher_for_Android_v0.6.zip)

**Comment by Mikiya83** [comment]
Very cool, the icon works well ! "About" section is clean and links to Rudez Studio so you should not have any problems with license ;) Thanks too for my links ! ^^ I think it's ready for a public release 1.0 !

edit : the last thing that needs a little improvement for me is the password button like i said before, good job for this app !

**Comment by Sky-84** [comment]
I removed the password button as you suggested and I made some little GUI improvements :).
In attach the new version.
I'm waiting to public the first release because I found another bug :S.
[hbs_decipher_for_Android_v0.7.zip](https://github.com/Sky-84/hbs_decipher_for_Android/files/2848790/hbs_decipher_for_Android_v0.7.zip)

**Comment by Mikiya83** [comment]
Yeah good job ! Now i mark all ideas as checked !
What is this last bug ?

**Comment by Sky-84** [comment]
> What is this last bug ?

It's related to write permission on external SD card (also known as removable storage). It seems that the "normal" write permission (requested at app start) it's not enough and it must be managed in a different way.
